$ $XConsortium: UAS_Base.msg /main/4 1996/08/16 18:07:29 cde-hal $

$set	Set_UAS_Base
$ 
$ messages specific to UAS/Base modules
$ 
1	"No access part provided in locator (URL)."
2	"Don't know how to create %s: objects"

$ In the following, do not translate any part of "UAS_ObjList<T>::operator[]"
3	"Range Error: UAS_ObjList<T>::operator[]"
4	"Range Error: UAS_PtrList<T>::operator[]"

$ $XConsortium: DtSR_Parser.msg /main/5 1996/08/16 18:07:41 cde-hal $

$set	Set_DtSR_Parser
$ 
$ messages specific to UAS/DtSearch modules
$ 
1	"The ``%s'' Search feature is not supported."
2	"quoted phrase"
3	"weight"
4	"proximity"
$	5	"xor" == Exclusive OR (Boolean)
5	"xor"


$set	Set_DtSR_SearchEngine
$ 
$ messages specific to UAS/DtSR_SearchEngine modules
$ 
1	"DtSearch does not support the query."

$ $XConsortium: UAS_MMDB.msg /main/4 1996/08/16 18:09:41 cde-hal $

$set	Set_UAS_MMDB
$ 
$ messages specific to UAS/MMDB modules
$ 
1	"The following bookcases are not valid:"
2	"Invalid Infolib path: %s"
3	"Ignoring invalid Infolib path: %s"
4	"DtMmdb Library %d"
5	"DtMmdb Infolib: "
6	"Infolib %s"

