$ $XConsortium: DtSR_Parser.msg /main/5 1996/08/16 18:07:41 cde-hal $

$set	Set_DtSR_Parser
$ 
$ messages specific to UAS/DtSearch modules
$ 
1	"The ``%s'' Search feature is not supported."
2	"quoted phrase"
3	"weight"
4	"proximity"
$	5	"xor" == Exclusive OR (Boolean)
5	"xor"


$set	Set_DtSR_SearchEngine
$ 
$ messages specific to UAS/DtSR_SearchEngine modules
$ 
1	"DtSearch does not support the query."

