/* : : generated from /home/kyiimn/Projects/cdesktopenv/cde/programs/dtksh/ksh93/src/cmd/ksh93/features/math.sh by iffe version 2022-01-09 : : */
#ifndef _def_math_ksh93
#define _def_math_ksh93	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _LIB_m	1	 
#define _LIB_ast	1	/* /home/kyiimn/Projects/cdesktopenv/cde/programs/dtksh/ksh93/arch/linux.i386-64/lib/libast.a is a library */
#define _LIB_util	1	 
#define _LIB_md	1	 
#define _LIB_cmd	1	/* /home/kyiimn/Projects/cdesktopenv/cde/programs/dtksh/ksh93/arch/linux.i386-64/lib/libcmd.a is a library */
#define _LIB_dll	1	/* /home/kyiimn/Projects/cdesktopenv/cde/programs/dtksh/ksh93/arch/linux.i386-64/lib/libdll.a is a library */
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

/* : : generated by iffe from /home/kyiimn/Projects/cdesktopenv/cde/programs/dtksh/ksh93/src/cmd/ksh93/data/math.tab : : */

typedef Sfdouble_t (*Math_f)(Sfdouble_t,...);

#include <ast_standards.h>
#include <math.h>
#include <ast_float.h>
#if defined(__ia64__) && defined(signbit)
# if defined __GNUC__ && __GNUC__ >= 4
#  define __signbitl(f)		__builtin_signbitl(f)
# else
#  if _lib_copysignl
#   define __signbitl(f)	(int)(copysignl(1.0,(f))<0.0)
#  endif
# endif
#endif

static Sfdouble_t local_float(Sfdouble_t a1){return a1;}
static int local_fpclassify(Sfdouble_t a1){return fpclassify(a1);}
static Sfdouble_t local_int(Sfdouble_t a1){return (a1 < LDBL_LLONG_MIN || a1 > LDBL_ULLONG_MAX) ? (Sfdouble_t)0 : (a1 < 0) ? (Sfdouble_t)((Sflong_t)a1) : (Sfdouble_t)((Sfulong_t)a1);}
static int local_isfinite(Sfdouble_t a1){return isfinite(a1);}
static int local_isgreater(Sfdouble_t a1,Sfdouble_t a2){return isgreater(a1,a2);}
static int local_isgreaterequal(Sfdouble_t a1,Sfdouble_t a2){return isgreaterequal(a1,a2);}
static int local_isless(Sfdouble_t a1,Sfdouble_t a2){return isless(a1,a2);}
static int local_islessequal(Sfdouble_t a1,Sfdouble_t a2){return islessequal(a1,a2);}
static int local_islessgreater(Sfdouble_t a1,Sfdouble_t a2){return islessgreater(a1,a2);}
static int local_isnormal(Sfdouble_t a1){return isnormal(a1);}
static int local_issubnormal(Sfdouble_t a1){return issubnormal(a1);}
static int local_isunordered(Sfdouble_t a1,Sfdouble_t a2){return isunordered(a1,a2);}
static int local_iszero(Sfdouble_t a1){return iszero(a1);}
static int local_signbit(Sfdouble_t a1){return signbit(a1);}

/*
 * first byte is two-digit octal number.  Last digit is number of args
 * first digit is 0 if return value is double, 1 for integer
 */
const struct mathtab shtab_math[] =
{
	"\001acos",	(Math_f)acosl,
	"\001acosh",	(Math_f)acoshl,
	"\001asin",	(Math_f)asinl,
	"\001asinh",	(Math_f)asinhl,
	"\001atan",	(Math_f)atanl,
	"\002atan2",	(Math_f)atan2l,
	"\001atanh",	(Math_f)atanhl,
	"\001cbrt",	(Math_f)cbrtl,
	"\001ceil",	(Math_f)ceill,
	"\002copysign",	(Math_f)copysignl,
	"\001cos",	(Math_f)cosl,
	"\001cosh",	(Math_f)coshl,
	"\001erf",	(Math_f)erfl,
	"\001erfc",	(Math_f)erfcl,
	"\001exp",	(Math_f)expl,
	"\001exp2",	(Math_f)exp2l,
	"\001exp10",	(Math_f)exp10l,
	"\001expm1",	(Math_f)expm1l,
	"\001fabs",	(Math_f)fabsl,
	"\001abs",	(Math_f)fabsl,
	"\002fdim",	(Math_f)fdiml,
	"\001finite",	(Math_f)finitel,
	"\001float",	(Math_f)local_float,
	"\001floor",	(Math_f)floorl,
	"\003fma",	(Math_f)fmal,
	"\002fmax",	(Math_f)fmaxl,
	"\002fmin",	(Math_f)fminl,
	"\002fmod",	(Math_f)fmodl,
	"\011fpclassify",	(Math_f)local_fpclassify,
	"\002hypot",	(Math_f)hypotl,
	"\011ilogb",	(Math_f)ilogbl,
	"\001int",	(Math_f)local_int,
	"\011isfinite",	(Math_f)local_isfinite,
	"\012isgreater",	(Math_f)local_isgreater,
	"\012isgreaterequal",	(Math_f)local_isgreaterequal,
	"\011isinf",	(Math_f)isinfl,
	"\012isless",	(Math_f)local_isless,
	"\012islessequal",	(Math_f)local_islessequal,
	"\012islessgreater",	(Math_f)local_islessgreater,
	"\011isnan",	(Math_f)isnanl,
	"\011isnormal",	(Math_f)local_isnormal,
	"\011issubnormal",	(Math_f)local_issubnormal,
	"\012isunordered",	(Math_f)local_isunordered,
	"\011iszero",	(Math_f)local_iszero,
	"\001j0",	(Math_f)j0l,
	"\001j1",	(Math_f)j1l,
	"\002jn",	(Math_f)jnl,
	"\042ldexp",	(Math_f)ldexpl,
	"\001lgamma",	(Math_f)lgammal,
	"\001log",	(Math_f)logl,
	"\001log10",	(Math_f)log10l,
	"\001log1p",	(Math_f)log1pl,
	"\001log2",	(Math_f)log2l,
	"\001logb",	(Math_f)logbl,
	"\001nearbyint",	(Math_f)nearbyintl,
	"\002nextafter",	(Math_f)nextafterl,
	"\002nexttoward",	(Math_f)nexttowardl,
	"\002pow",	(Math_f)powl,
	"\002remainder",	(Math_f)remainderl,
	"\001rint",	(Math_f)rintl,
	"\001round",	(Math_f)roundl,
	"\002scalb",	(Math_f)scalbl,
	"\002scalbn",	(Math_f)scalbnl,
	"\011signbit",	(Math_f)local_signbit,
	"\001sin",	(Math_f)sinl,
	"\001sinh",	(Math_f)sinhl,
	"\001sqrt",	(Math_f)sqrtl,
	"\001tan",	(Math_f)tanl,
	"\001tanh",	(Math_f)tanhl,
	"\001tgamma",	(Math_f)tgammal,
	"\001trunc",	(Math_f)truncl,
	"\001y0",	(Math_f)y0l,
	"\001y1",	(Math_f)y1l,
	"\002yn",	(Math_f)ynl,
	"",		(Math_f)0
};
#endif
